### PR TITLE
FEATURE: some `Makefile` rules to make compilation easier

### PR DESCRIPTION
**Pull request by amtoine**
i thought adding very simple `Makefile` rules to compile, run the application and clean the repo could be helpful :relieved: 

i never remember the `cmake` commands and copy-pasting them from the `README` is not the best to me :thinking: 

this PR adds
- `make build` to compile the source
- `make run` to run the compiled application => it takes care of the `cd bin`
- `make clean` to clean the compilation files

there is also a little note in the `README` to link users to the `Makefile` :+1: 

> **Note**
> see the [`README`](https://github.com/amtoine/wiresmash/tree/feature/little-makefile-wrapper-to-compile#building-with-cmake) and the [`rules`](https://github.com/amtoine/wiresmash/blob/feature/little-makefile-wrapper-to-compile/Makefile)

### CODE REVIEW

**Comment by gbrivady** [comment]
@amtoine GitHub reports a merge conflict, could you look into it so we can move on?

**Comment by amtoine** [comment]
@gbrivady
should be good in 37c3438f9f93db6de911e8f5d04f4a6c8d9ffee5 :wink:

**Review by gbrivady — APPROVED** [review]

**Comment by amtoine** [comment]
who could review this?

**Comment by amtoine** [comment]
we can also bring the required approvals to only one :+1:

**Comment by gbrivady** [comment]
@atxr or @ctmbl if you have 5 seconds to check the makefile

**Comment by amtoine** [comment]
> I think it would be best if we could have 2 approvals for some stuff (features), and 1 for others (README/Contributing/wikis/typos etc...)
>
mm not sure how feasible that is to have different number of approvals :thinking:

**Comment by gbrivady** [comment]
> > I think it would be best if we could have 2 approvals for some stuff (features), and 1 for others (README/Contributing/wikis/typos etc...)
> 
> mm not sure how feasible that is to have different number of approvals 🤔

Doesnt seem possible. Since we are in early development and it doesn't bear that much risk, I will set it to only one review. Can always use a two-branch system (ie fast reviews/slow reviews) if needed later down the line.

**Comment by amtoine** [comment]
lol i modified your message sorry...
too much work to revert though :sob:

**Comment by amtoine** [comment]
wanted to say that, if you feel ok with not waiting for the reviewers, you can merge this safely :relieved:

**Pull request merged**
