### PR TITLE
Add engine namespace

### LINKED ISSUE #24: Add engine namespace
Project issue, to track #20. View said issue for more info

### PR DESCRIPTION
**Pull request by gbrivady**
Close #24. Basically, add every file under the `src/engine` path to the namespace `Engine`. 

Also add to fix a bunch of other files to fit with the new namespace (basically just appended `Engine::...` to a bunch of stuff).

If it compiles, it should be good to go and good enough for a review. Try to check if I missed any file, but should be a-ok.

Choose to go with CamlCase for namespace format, because it looks prettier imo. Can be changed back to `engine` with a simple Ctrl+F anyway.

### CODE REVIEW

**Comment by bassetmatt** [comment]
The styling convention for the namespace isn't consistent.

In 
- `box/box.h`
- `box/rectangle.h`
- `input/input_handler.h`
- `physics/kinematics.h`
- `physics/phxbox.h`
- `physics/point.h`

there is:
```cpp
namespace Engine {
//code
}
```

In `entity.h`, there's a newline:
```cpp
namespace Engine
{
//code
}
```

In `universe_master.h`, there isn't any space after the namespace name:
```cpp
namespace Engine{
//code
}
```

**Comment by gbrivady** [comment]
> The styling convention for the namespace isn't consistent.

Fixed in b2d034f

**Comment by bassetmatt** [comment]
Works on my machine

**Review by bassetmatt — APPROVED** [review]
Seems okay, reviewed it

**Pull request merged**
